import type { ParserTemplateDefinition } from "./types";

type BaselineParserTemplateDefinition = Omit<
  ParserTemplateDefinition,
  | "accountIdentifiers"
  | "identityTextFragments"
  | "templateKind"
  | "builtInTemplateId"
  | "engineEditable"
  | "userProfile"
>;

const DEFAULT_PARSER_TEMPLATES: readonly BaselineParserTemplateDefinition[] = [
  {
    id: "cbe_debit_v1",
    financialInstitution: "cbe",
    institutionKey: "CBE",
    institutionLabel: "Commercial Bank of Ethiopia",
    institutionIcon: "account_balance",
    senderAliases: ["CBE"],
    name: "CBE Debit Alert",
    version: "v1.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "account\\s(?<account>\\d{3,})\\swas debited with ETB\\s*(?<amount>[\\d,.]+)\\son\\s(?<date>\\d{4}-\\d{2}-\\d{2})\\sat\\s(?<merchant>.+?)\\.\\sBal ETB\\s*(?<balance>[\\d,.]+)",
    note: "Direct debit alert with merchant and running balance capture.",
    healthScore: 99.2,
    sourceType: "core",
    direction: "debit",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    accountKey: "account",
    dateKey: "date",
    dateMode: "message_date",
  },
  {
    id: "cbe_credit_v1",
    financialInstitution: "cbe",
    institutionKey: "CBE",
    institutionLabel: "Commercial Bank of Ethiopia",
    institutionIcon: "account_balance",
    senderAliases: ["CBE"],
    name: "CBE Credit Alert",
    version: "v1.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "Acct\\s(?<account>\\d{3,})\\scredited with ETB\\s*(?<amount>[\\d,.]+)\\son\\s(?<date>\\d{4}-\\d{2}-\\d{2})\\sfrom\\s(?<merchant>.+?)\\.\\sBal ETB\\s*(?<balance>[\\d,.]+)",
    note: "Direct credit alert with sender and running balance capture.",
    healthScore: 98.8,
    sourceType: "core",
    direction: "credit",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    accountKey: "account",
    dateKey: "date",
    dateMode: "message_date",
  },
  {
    id: "cbe_received_to_account_v1",
    financialInstitution: "cbe",
    institutionKey: "CBE",
    institutionLabel: "Commercial Bank of Ethiopia",
    institutionIcon: "account_balance",
    senderAliases: ["CBE"],
    name: "CBE Incoming Transfer",
    version: "v1.0.0",
    updated: "Core template",
    status: "fallback",
    regex:
      "received ETB\\s*(?<amount>[\\d,.]+)\\s+from account\\s+.+?\\((?<merchant>.+?)\\)\\s+to your account\\s+(?<account>\\d{3,}).*?current balance is ETB\\s*(?<balance>[\\d,.]+)",
    note: "Incoming transfer routed into a personal CBE account.",
    healthScore: 96.1,
    sourceType: "core",
    direction: "credit",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    accountKey: "account",
    dateMode: "captured_at",
  },
  {
    id: "cbe_debit_masked_v2",
    financialInstitution: "cbe",
    institutionKey: "CBE",
    institutionLabel: "Commercial Bank of Ethiopia",
    institutionIcon: "account_balance",
    senderAliases: ["CBE"],
    name: "CBE Masked Debit",
    version: "v2.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "Account\\s(?:\\d[\\d*]*?)(?<account>\\d{3,4})\\shas been debited with ETB\\s*(?<amount>[\\d,.]+).*?(?:Service charge of\\s+ETB\\s*(?<fee>[\\d,.]+))?.*?(?:VAT\\(15%\\)\\s+of ETB\\s*(?<vat>[\\d,.]+))?.*?(?:Disaster Fund \\(5%\\)\\s+of ETB\\s*(?<extraFee>[\\d,.]+))?.*?(?:with a total of ETB\\s*(?<total>[\\d,.]+))?.*?Current Balance is ETB\\s*(?<balance>[\\d,.]+)",
    note: "Masked-account debit route with charge, VAT, and disaster-fund support.",
    healthScore: 97.9,
    sourceType: "core",
    direction: "debit",
    amountKey: "amount",
    balanceKey: "balance",
    feeKey: "fee",
    vatKey: "vat",
    extraFeeKey: "extraFee",
    totalKey: "total",
    accountKey: "account",
    referenceKey: "reference",
    dateMode: "captured_at",
  },
  {
    id: "cbe_credit_masked_v2",
    financialInstitution: "cbe",
    institutionKey: "CBE",
    institutionLabel: "Commercial Bank of Ethiopia",
    institutionIcon: "account_balance",
    senderAliases: ["CBE"],
    name: "CBE Masked Credit",
    version: "v2.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "Account\\s(?:\\d[\\d*]*?)(?<account>\\d{3,4})\\shas been Credited with ETB\\s*(?<amount>[\\d,.]+)\\s+from\\s+(?<merchant>.+?),\\s+on\\s+(?<date>\\d{2}/\\d{2}/\\d{4})\\s+at\\s+(?<time>\\d{2}:\\d{2}:\\d{2})(?:\\s*(?<meridiem>AM|PM))?.*?Ref No\\s+(?<reference>[A-Z0-9]+).*?Current Balance is ETB\\s*(?<balance>[\\d,.]+)",
    note: "Masked-account credit route with named sender and reference capture.",
    healthScore: 97.4,
    sourceType: "core",
    direction: "credit",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    accountKey: "account",
    referenceKey: "reference",
    dateKey: "date",
    timeKey: "time",
    meridiemKey: "meridiem",
    dateMode: "message_date",
  },
  {
    id: "cbe_transfer_masked_v2",
    financialInstitution: "cbe",
    institutionKey: "CBE",
    institutionLabel: "Commercial Bank of Ethiopia",
    institutionIcon: "account_balance",
    senderAliases: ["CBE"],
    name: "CBE Masked Transfer",
    version: "v2.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "transfer(?:ed|red)\\s+ETB\\s*(?<amount>[\\d,.]+)\\s+to\\s+(?<merchant>.+?)\\s+on\\s+(?<date>\\d{2}/\\d{2}/\\d{4})\\s+at\\s+(?<time>\\d{2}:\\d{2}:\\d{2})\\s+from your account\\s+(?:\\d[\\d*]*?)(?<account>\\d{3,4}).*?(?:S\\.charge of ETB|Service charge of\\s+ETB)\\s*(?<fee>[\\d,.]+).*?(?:VAT\\(15%\\)|15% VAT)\\s+of ETB\\s*(?<vat>[\\d,.]+).*?(?:Disaster Fund \\(5%\\) of ETB\\s*(?<extraFee>[\\d,.]+))?.*?with a total of ETB\\s*(?<total>[\\d,.]+).*?Current Balance is ETB\\s*(?<balance>[\\d,.]+)",
    note: "Masked-account transfer route with charge, VAT, disaster fund, and current balance.",
    healthScore: 96.9,
    sourceType: "core",
    direction: "transfer",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    feeKey: "fee",
    vatKey: "vat",
    extraFeeKey: "extraFee",
    totalKey: "total",
    accountKey: "account",
    dateKey: "date",
    timeKey: "time",
    dateMode: "message_date",
  },
  {
    id: "dashen_debit_masked_v2",
    financialInstitution: "dashen",
    institutionKey: "DashenBank",
    institutionLabel: "Dashen Bank",
    institutionIcon: "account_balance",
    senderAliases: ["DashenBank", "Dashen"],
    name: "Dashen Debit",
    version: "v2.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "your account\\s+'?(?:\\d[\\d*]*?)(?<account>\\d{3})'?\\s+(?:is|has been)\\s+debited with ETB\\s*(?<amount>[\\d,.]+)\\s+on\\s+(?<date>(?:\\d{4}-\\d{2}-\\d{2})|(?:\\d{2}/\\d{2}/\\d{4}))(?:\\s+at\\s+(?<time>\\d{2}:\\d{2}:\\d{2})\\s*(?<meridiem>AM|PM)?)?.*?(?:service fee of ETB\\s*(?<fee>[\\d,.]+))?.*?(?:VAT of ETB\\s*(?<vat>[\\d,.]+))?.*?current balance is ETB\\s*(?<balance>[\\d,.]+)",
    note: "Dashen debit route covering older alerts and Super App debit messages.",
    healthScore: 96.7,
    sourceType: "core",
    direction: "debit",
    amountKey: "amount",
    balanceKey: "balance",
    feeKey: "fee",
    vatKey: "vat",
    accountKey: "account",
    dateKey: "date",
    timeKey: "time",
    meridiemKey: "meridiem",
    dateMode: "message_date",
  },
  {
    id: "dashen_credit_masked_v2",
    financialInstitution: "dashen",
    institutionKey: "DashenBank",
    institutionLabel: "Dashen Bank",
    institutionIcon: "account_balance",
    senderAliases: ["DashenBank", "Dashen"],
    name: "Dashen Credit",
    version: "v2.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "your account\\s+'?(?:\\d[\\d*]*?)(?<account>\\d{3})'?\\s+has been credited with ETB\\s*(?<amount>[\\d,.]+)(?:\\s+from\\s+(?<merchant>.+?))?\\s+on\\s+(?<date>(?:\\d{4}-\\d{2}-\\d{2})|(?:\\d{2}/\\d{2}/\\d{4}))(?:\\s+at\\s+(?<time>\\d{2}:\\d{2}:\\d{2})\\s*(?<meridiem>AM|PM)?)?.*?current balance is ETB\\s*(?<balance>[\\d,.]+)",
    note: "Dashen credit route for direct credits and incoming other-bank deposits.",
    healthScore: 95.8,
    sourceType: "core",
    direction: "credit",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    accountKey: "account",
    dateKey: "date",
    timeKey: "time",
    meridiemKey: "meridiem",
    dateMode: "message_date",
  },
  {
    id: "dashen_transfer_to_wallet_v1",
    financialInstitution: "dashen",
    institutionKey: "DashenBank",
    institutionLabel: "Dashen Bank",
    institutionIcon: "account_balance",
    senderAliases: ["DashenBank", "Dashen"],
    name: "Dashen To Telebirr Transfer",
    version: "v1.0.0",
    updated: "Core template",
    status: "fallback",
    regex:
      "ETB\\s*(?<amount>[\\d,.]+)\\s+has been debited from your account\\s+(?:\\d[\\d*]*?)(?<account>\\d{3})\\s+and credited to the\\s+(?<merchant>Telebirr account\\s+\\+?\\d+)\\s+on\\s+(?<date>\\d{4}-\\d{2}-\\d{2})\\s+at\\s+(?<time>\\d{2}:\\d{2}:\\d{2}).*?(?:service fee of ETB\\s*(?<fee>[\\d,.]+))?.*?(?:VAT of ETB\\s*(?<vat>[\\d,.]+))?.*?current balance is ETB\\s*(?<balance>[\\d,.]+)",
    note: "Explicit Dashen transfer into a Telebirr wallet.",
    healthScore: 94.9,
    sourceType: "core",
    direction: "transfer",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    feeKey: "fee",
    vatKey: "vat",
    accountKey: "account",
    dateKey: "date",
    timeKey: "time",
    dateMode: "message_date",
  },
  {
    id: "telebirr_paid_goods_v1",
    financialInstitution: "telebirr",
    institutionKey: "127",
    institutionLabel: "Telebirr",
    institutionIcon: "account_balance_wallet",
    senderAliases: ["127", "Telebirr"],
    name: "Telebirr Goods Payment",
    version: "v1.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "paid ETB\\s*(?<amount>[\\d,.]+)\\s+(?:for goods purchased from|goods purchased from|for fuel purchased from)\\s+(?<merchant>.+?)\\s+on\\s+(?<date>\\d{2}/\\d{2}/\\d{4}|\\d{4}-\\d{2}-\\d{2})\\s+(?<time>\\d{2}:\\d{2}:\\d{2}).*?(?:service fee(?: is)?\\s*ETB\\s*(?<fee>[\\d,.]+))?.*?(?:VAT on the service fee is ETB\\s*(?<vat>[\\d,.]+))?.*?current(?: E-Money Account| Account)? balance is ETB\\s*(?<balance>[\\d,.]+)",
    note: "Telebirr merchant and utility purchases with optional service fee and VAT.",
    healthScore: 97.5,
    sourceType: "core",
    direction: "debit",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    feeKey: "fee",
    vatKey: "vat",
    dateKey: "date",
    timeKey: "time",
    dateMode: "message_date",
    accountChannel: "mobile_money",
  },
  {
    id: "telebirr_paid_package_v2",
    financialInstitution: "telebirr",
    institutionKey: "127",
    institutionLabel: "Telebirr",
    institutionIcon: "account_balance_wallet",
    senderAliases: ["127", "Telebirr"],
    name: "Telebirr Package Purchase",
    version: "v2.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "paid ETB\\s*(?<amount>[\\d,.]+)\\s+for package\\s+(?<merchant>.+?)\\s+purchase made for\\s+(?<account>\\d+)\\s+on\\s+(?<date>\\d{2}/\\d{2}/\\d{4})\\s+(?<time>\\d{2}:\\d{2}:\\d{2}).*?transaction number is\\s+(?<reference>[A-Z0-9]+).*?current balance is ETB\\s*(?<balance>[\\d,.]+)",
    note: "Telebirr package purchase route keyed by target phone number.",
    healthScore: 96.4,
    sourceType: "core",
    direction: "debit",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    accountKey: "account",
    referenceKey: "reference",
    dateKey: "date",
    timeKey: "time",
    dateMode: "message_date",
    accountChannel: "mobile_money",
  },
  {
    id: "telebirr_transfer_bank_v2",
    financialInstitution: "telebirr",
    institutionKey: "127",
    institutionLabel: "Telebirr",
    institutionIcon: "account_balance_wallet",
    senderAliases: ["127", "Telebirr"],
    name: "Telebirr Bank Transfer",
    version: "v2.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "transferred ETB\\s*(?<amount>[\\d,.]+)\\s+successfully from your telebirr account\\s*(?<wallet>\\d+)?\\s+to\\s+(?<merchant>.+?)\\s+account number\\s+(?<account>\\d+)\\s+on\\s+(?<date>\\d{2}/\\d{2}/\\d{4})\\s+(?<time>\\d{2}:\\d{2}:\\d{2}).*?telebirr transaction number is\\s+(?<telebirrReference>[A-Z0-9]+)\\s+and your bank transaction number is\\s+(?<reference>[A-Za-z0-9]+).*?(?:service fee is\\s*ETB\\s*(?<fee>[\\d,.]+))?.*?(?:(?:15%\\s+)?VAT on the service fee is ETB\\s*(?<vat>[\\d,.]+))?.*?current balance is ETB\\s*(?<balance>[\\d,.]+)",
    note: "Telebirr transfer into a bank account with separated bank and wallet references.",
    healthScore: 97.2,
    sourceType: "core",
    direction: "transfer",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    feeKey: "fee",
    vatKey: "vat",
    accountKey: "account",
    referenceKey: "reference",
    dateKey: "date",
    timeKey: "time",
    dateMode: "message_date",
    accountChannel: "mobile_money",
  },
  {
    id: "telebirr_transfer_v1",
    financialInstitution: "telebirr",
    institutionKey: "127",
    institutionLabel: "Telebirr",
    institutionIcon: "account_balance_wallet",
    senderAliases: ["127", "Telebirr"],
    name: "Telebirr P2P Transfer",
    version: "v1.0.0",
    updated: "Core template",
    status: "fallback",
    regex:
      "transferred ETB\\s*(?<amount>[\\d,.]+)\\s+to\\s+(?<merchant>.+?)\\s+on\\s+(?<date>\\d{2}/\\d{2}/\\d{4})\\s+(?<time>\\d{2}:\\d{2}:\\d{2}).*?transaction number is\\s+(?<reference>[A-Z0-9]+).*?(?:service fee is\\s*ETB\\s*(?<fee>[\\d,.]+))?.*?(?:(?:15%\\s+)?VAT on the service fee is ETB\\s*(?<vat>[\\d,.]+))?.*?current E-Money Account\\s+balance is ETB\\s*(?<balance>[\\d,.]+)",
    note: "Wallet-to-wallet transfer route with service fee and VAT capture.",
    healthScore: 95.1,
    sourceType: "core",
    direction: "transfer",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    feeKey: "fee",
    vatKey: "vat",
    referenceKey: "reference",
    dateKey: "date",
    timeKey: "time",
    dateMode: "message_date",
    accountChannel: "mobile_money",
  },
  {
    id: "telebirr_bank_credit_v3",
    financialInstitution: "telebirr",
    institutionKey: "127",
    institutionLabel: "Telebirr",
    institutionIcon: "account_balance_wallet",
    senderAliases: ["127", "Telebirr"],
    name: "Telebirr Bank Incoming",
    version: "v3.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "received\\s+ETB\\s*(?<amount>[\\d,.]+)\\s+by transaction number\\s+(?<reference>[A-Z0-9]+)\\s+on\\s+(?<date>\\d{4}-\\d{2}-\\d{2})\\s+(?<time>\\d{2}:\\d{2}:\\d{2})\\s+from\\s+(?<merchant>.+?)\\s+to your telebirr Account\\s+(?<account>\\d+).*?current balance is ETB\\s*(?<balance>[\\d,.]+)",
    note: "Incoming bank-to-wallet transfer with bank sender and wallet balance.",
    healthScore: 98.1,
    sourceType: "core",
    direction: "credit",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    accountKey: "account",
    referenceKey: "reference",
    dateKey: "date",
    timeKey: "time",
    dateMode: "message_date",
    accountChannel: "mobile_money",
  },
  {
    id: "telebirr_credit_v2",
    financialInstitution: "telebirr",
    institutionKey: "127",
    institutionLabel: "Telebirr",
    institutionIcon: "account_balance_wallet",
    senderAliases: ["127", "Telebirr"],
    name: "Telebirr Direct Credit",
    version: "v2.0.0",
    updated: "Core template",
    status: "fallback",
    regex:
      "received\\s*(?<amount>[\\d,.]+)\\s*ETB\\s+from\\s+(?<merchant>.+?)\\.\\s+Your current balance is ETB\\s*(?<balance>[\\d,.]+)",
    note: "Short direct-credit format used in earlier wallet receipts.",
    healthScore: 94.6,
    sourceType: "core",
    direction: "credit",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    dateMode: "captured_at",
    accountChannel: "mobile_money",
  },
  {
    id: "telebirr_atm_withdrawal_v1",
    financialInstitution: "telebirr",
    institutionKey: "127",
    institutionLabel: "Telebirr",
    institutionIcon: "account_balance_wallet",
    senderAliases: ["127", "Telebirr"],
    name: "Telebirr ATM Cash-out",
    version: "v1.0.0",
    updated: "Core template",
    status: "fallback",
    regex:
      "request to withdraw ETB\\s*(?<amount>[\\d,.]+)\\s+from your telebirr account\\s+(?<account>\\d+)\\s+via secret code\\s+\\d+\\s+on\\s+(?<date>\\d{4}-\\d{2}-\\d{2})\\s+(?<time>\\d{2}:\\d{2}:\\d{2})\\s+using\\s+(?<merchant>.+?\\s+ATM)\\s+with transaction number\\s+(?<reference>[A-Z0-9]+)\\s+is successfully completed.*?service fee \\(including 15% VAT\\) is ETB\\s*(?<fee>[\\d,.]+).*?current Account balance is ETB\\s*(?<balance>[\\d,.]+)",
    note: "Completed ATM cash-out; excludes the earlier secret-code issue message.",
    healthScore: 95.9,
    sourceType: "core",
    direction: "debit",
    amountKey: "amount",
    merchantKey: "merchant",
    titleKey: "merchant",
    preserveTitleCase: true,
    balanceKey: "balance",
    feeKey: "fee",
    accountKey: "account",
    referenceKey: "reference",
    dateKey: "date",
    timeKey: "time",
    dateMode: "message_date",
    accountChannel: "mobile_money",
  },
  {
    id: "boa_debit_v1",
    financialInstitution: "boa",
    institutionKey: "BOA",
    institutionLabel: "Bank of Abyssinia",
    institutionIcon: "account_balance_wallet",
    senderAliases: ["BOA"],
    name: "BOA Debit",
    version: "v1.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "(?:was|has been)?\\s*debited with ETB\\s*(?<amount>[\\d,.]+).*?(?:(?:Info:\\s*|transfer description\\s+)(?<merchant>.+?)(?:\\.|\\s+(?:Avail\\. Bal:|available balance:|available balance in the account is ETB|the available balance in the account is ETB)))?.*?(?:Avail\\. Bal:|available balance:|available balance in the account is ETB|the available balance in the account is ETB)\\s*ETB\\s*(?<balance>[\\d,.]+)",
    note: "BOA debit and transfer alerts with info or transfer-description payloads.",
    healthScore: 95.3,
    sourceType: "core",
    direction: "debit",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    dateMode: "captured_at",
  },
  {
    id: "boa_credit_v1",
    financialInstitution: "boa",
    institutionKey: "BOA",
    institutionLabel: "Bank of Abyssinia",
    institutionIcon: "account_balance_wallet",
    senderAliases: ["BOA"],
    name: "BOA Credit",
    version: "v1.0.0",
    updated: "Core template",
    status: "fallback",
    regex:
      "credited with ETB\\s*(?<amount>[\\d,.]+).*?(?:transfer made by|from)\\s+(?<merchant>.+?)(?:\\s+through|,|\\.)",
    note: "BOA incoming transfer and deposit receipts.",
    healthScore: 91.8,
    sourceType: "core",
    direction: "credit",
    amountKey: "amount",
    merchantKey: "merchant",
    dateMode: "captured_at",
  },
  {
    id: "cbebirr_credit_v1",
    financialInstitution: "cbebirr",
    institutionKey: "CBEBirr",
    institutionLabel: "CBEBirr",
    institutionIcon: "account_balance_wallet",
    senderAliases: ["CBEBirr"],
    name: "CBEBirr Credit",
    version: "v1.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "account has been credited with\\s*(?<amount>[\\d,.]+)Br.*?Txn ID\\s+(?<reference>[A-Z0-9]+).*?balance is\\s*(?<balance>[\\d,.]+)Br",
    note: "CBEBirr balance credit with transaction ID and post-balance.",
    healthScore: 93.6,
    sourceType: "core",
    direction: "credit",
    amountKey: "amount",
    balanceKey: "balance",
    referenceKey: "reference",
    dateMode: "captured_at",
    accountChannel: "mobile_money",
  },
  {
    id: "cbebirr_transfer_v1",
    financialInstitution: "cbebirr",
    institutionKey: "CBEBirr",
    institutionLabel: "CBEBirr",
    institutionIcon: "account_balance_wallet",
    senderAliases: ["CBEBirr"],
    name: "CBEBirr Transfer",
    version: "v1.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "made\\s*(?<amount>[\\d,.]+)Br\\.\\s+transfer to\\s+(?<merchant>.+?)\\s+on.*?(?:Tax\\s*(?<vat>[\\d,.]+)Br\\.)?.*?(?:Charge\\s*(?<fee>[\\d,.]+)Br\\.)?.*?balance is\\s*(?<balance>[\\d,.]+)Br",
    note: "CBEBirr transfer with optional charge and tax components.",
    healthScore: 94.4,
    sourceType: "core",
    direction: "transfer",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    feeKey: "fee",
    vatKey: "vat",
    dateMode: "captured_at",
    accountChannel: "mobile_money",
  },
  {
    id: "cbebirr_airtime_purchase_v1",
    financialInstitution: "cbebirr",
    institutionKey: "CBEBirr",
    institutionLabel: "CBEBirr",
    institutionIcon: "account_balance_wallet",
    senderAliases: ["CBEBirr"],
    name: "CBEBirr Airtime Purchase",
    version: "v1.0.0",
    updated: "Core template",
    status: "fallback",
    regex:
      "bought\\s*(?<amount>[\\d,.]+)Br\\.\\s+of airtime for\\s+(?<merchant>.+?)\\s+on.*?balance is\\s*(?<balance>[\\d,.]+)Br",
    note: "CBEBirr airtime top-up routed as a wallet debit.",
    healthScore: 91.2,
    sourceType: "core",
    direction: "debit",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    dateMode: "captured_at",
    accountChannel: "mobile_money",
  },
  {
    id: "cbebirr_withdrawal_v1",
    financialInstitution: "cbebirr",
    institutionKey: "CBEBirr",
    institutionLabel: "CBEBirr",
    institutionIcon: "account_balance_wallet",
    senderAliases: ["CBEBirr"],
    name: "CBEBirr ATM Withdrawal",
    version: "v1.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "withdrawn\\s*(?<amount>[\\d,.]+)Br\\.\\s+from CBE ATM.*?(?:Tax\\s*(?<vat>[\\d,.]+)Br\\.)?.*?(?:Charge\\s*(?<fee>[\\d,.]+)Br\\.)?.*?balance is\\s*(?<balance>[\\d,.]+)Br",
    note: "CBEBirr ATM withdrawal with charge and tax components.",
    healthScore: 95.4,
    sourceType: "core",
    direction: "debit",
    amountKey: "amount",
    merchantKey: "merchant",
    titleKey: "merchant",
    preserveTitleCase: true,
    balanceKey: "balance",
    feeKey: "fee",
    vatKey: "vat",
    dateMode: "captured_at",
    accountChannel: "mobile_money",
  },
  {
    id: "bunna_credit_v1",
    financialInstitution: "bunna",
    institutionKey: "BunnaBank",
    institutionLabel: "Bunna Bank",
    institutionIcon: "account_balance",
    senderAliases: ["BunnaBank", "Bunna"],
    name: "Bunna Deposit",
    version: "v1.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "Deposit of\\s*(?<amount>[\\d,.]+)\\s*ETB\\s+has been made to your account\\s+(?<account>[\\d*]+)\\s+BY\\s+(?:FROM\\s+)?(?<merchant>.+?)\\s+on\\s+(?<date>\\d{2}-\\d{2}-\\d{4})\\s+(?<time>\\d{2}:\\d{2}:\\d{2}),\\s+your current balance is\\s+(?<balance>[\\d,.]+)\\s*ETB",
    note: "Bunna deposit route for self and named incoming deposits.",
    healthScore: 96.2,
    sourceType: "core",
    direction: "credit",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    accountKey: "account",
    dateKey: "date",
    timeKey: "time",
    dateMode: "message_date",
  },
  {
    id: "bunna_withdrawal_v1",
    financialInstitution: "bunna",
    institutionKey: "BunnaBank",
    institutionLabel: "Bunna Bank",
    institutionIcon: "account_balance",
    senderAliases: ["BunnaBank", "Bunna"],
    name: "Bunna Withdrawal",
    version: "v1.0.0",
    updated: "Core template",
    status: "active",
    regex:
      "Withdrawal of\\s*(?<amount>[\\d,.]+)\\s*ETB\\s+has been made from your account\\s+(?<account>[\\d*]+)\\s+on\\s+(?<date>\\d{2}-\\d{2}-\\d{4})\\s+(?<time>\\d{2}:\\d{2}:\\d{2})\\s+by\\s+(?<merchant>.+?)(?:,|\\s+)your current balance is\\s*(?<balance>[\\d,.]+)\\s*ETB",
    note: "Bunna withdrawal route with account balance and origin descriptor.",
    healthScore: 95.7,
    sourceType: "core",
    direction: "debit",
    amountKey: "amount",
    merchantKey: "merchant",
    balanceKey: "balance",
    accountKey: "account",
    dateKey: "date",
    timeKey: "time",
    dateMode: "message_date",
  },
 ] as const;

function resolveBaselineTemplate(
  template: BaselineParserTemplateDefinition,
): ParserTemplateDefinition {
  return {
    ...template,
    accountIdentifiers: [],
    identityTextFragments: [],
    templateKind: "builtin",
    builtInTemplateId: template.id,
    engineEditable: false,
    userProfile: {
      senderAliases: [...template.senderAliases],
      accountIdentifiers: [],
      identityTextFragments: [],
    },
  };
}

export function cloneDefaultParserTemplates(): ParserTemplateDefinition[] {
  return DEFAULT_PARSER_TEMPLATES.map((template) =>
    resolveBaselineTemplate({
      ...template,
      senderAliases: [...template.senderAliases],
    }),
  );
}

export function findDefaultParserTemplate(
  templateId: string,
): ParserTemplateDefinition | undefined {
  const template = DEFAULT_PARSER_TEMPLATES.find((entry) => entry.id === templateId);
  if (!template) {
    return undefined;
  }

  return resolveBaselineTemplate({
    ...template,
    senderAliases: [...template.senderAliases],
  });
}

export { DEFAULT_PARSER_TEMPLATES };
